In [1]:
!pip install kaggle

Requirement already satisfied: kaggle in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (1.6.12)
Requirement already satisfied: six>=1.10 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from kaggle) (1.16.0)
Requirement already satisfied: certifi>=2023.7.22 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from kaggle) (2024.2.2)
Requirement already satisfied: python-dateutil in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from kaggle) (2.9.0.post0)
Requirement already satisfied: requests in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from kaggle) (2.31.0)
Requirement already satisfied: tqdm in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from kaggle) (4.66.4)
Requirement already satisfied: python-slugify in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from kaggle) (8.0.4)
Requirement already satisfied: urllib3 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from kaggle) (2.2.1)
Requirement already satisfied: bleach in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from kaggle) (6.1.0)
Requirement already satisfied: webencodings in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from bleach->kaggle) (0.5.1)
Requirement already satisfied: text-unidecode>=1.3 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from python-slugify->kaggle) (1.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from requests->kaggle) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from requests->kaggle) (3.7)
Requirement already satisfied: colorama in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from tqdm->kaggle) (0.4.6)

WARNING: You are using pip version 21.1.1; however, version 24.0 is available.
You should consider upgrading via the 'c:\users\lenovo\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.

In [124]:
# download dataset with kaggle api
import kaggle
!kaggle datasets download vineetpatyal/retail-order-dataset -f orders.csv

Dataset URL: https://www.kaggle.com/datasets/vineetpatyal/retail-order-dataset
License(s): unknown
Downloading orders.csv.zip to C:\Users\lenovo\Desktop\DA Projects\Complete\Python\Retail Orders SQL+Python

  0%|          | 0.00/200k [00:00<?, ?B/s]
100%|##########| 200k/200k [00:00<00:00, 208kB/s]
100%|##########| 200k/200k [00:00<00:00, 208kB/s]

In [6]:
#1 Extract file from zip file

In [1]:
import zipfile
zip_ref = zipfile.ZipFile('orders.csv.zip')
zip_ref.extractall() # extract file to directory
zip_ref.close() #close file

In [2]:
#2 Read data from the file and handle null values
import pandas as pd

In [3]:
df = pd.read_csv('orders.csv',na_values=['Not Available', 'unknown'])
df['Ship Mode'].unique()

array(['Second Class', 'Standard Class', nan, 'First Class', 'Same Day'],
      dtype=object)

In [4]:
df.head(10)

,Order Id,Order Date,Ship Mode,Segment,Country,City,State,Postal Code,Region,Category,Sub Category,Product Id,cost price,List Price,Quantity,Discount Percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,NaN,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3

In [17]:
#3 rename columns names, make them lower case and repalce space with underscore

In [5]:
df.columns=df.columns.str.lower()

In [6]:
df.columns = df.columns.str.replace(' ','_' )

In [7]:
df.head(10)

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5
5,6,2022-03-13,NaN,Consumer,United States,Los Angeles,California,90032,West,Furniture,Furnishings,FUR-FU-10001487,50,50,7,3
6,7,2022-12-28,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Art,OFF-AR-10002833,10,10,4,3
7,8,2022-01-25,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Technology,Phones,TEC-PH-10002275,860,910,6,5
8,9,2023-03-23,NaN,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Binders,OFF-BI-10003910,20,20,3,2
9,10,2023-05-16,Standard Class,Consumer,United States,Los Angeles,California,90032,West,Office Supplies,Appliances,OFF-AP-10002892,90,110,5,3

In [35]:
#4 Derive new columns discount, sale price and profit

In [8]:
df['discount']= df['list_price']*df['discount_percent']*.01
df['sale_price'] = df['list_price']-df['discount']
df['profit'] = df['sale_price']-df['cost_price']

In [8]:
df.head()

,order_id,order_date,ship_mode,segment,country,city,state,postal_code,region,category,sub_category,product_id,cost_price,list_price,quantity,discount_percent,discount,sale_price,profit
0,1,2023-03-01,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Bookcases,FUR-BO-10001798,240,260,2,2,5.2,254.8,14.8
1,2,2023-08-15,Second Class,Consumer,United States,Henderson,Kentucky,42420,South,Furniture,Chairs,FUR-CH-10000454,600,730,3,3,21.9,708.1,108.1
2,3,2023-01-10,Second Class,Corporate,United States,Los Angeles,California,90036,West,Office Supplies,Labels,OFF-LA-10000240,10,10,2,5,0.5,9.5,-0.5
3,4,2022-06-18,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Furniture,Tables,FUR-TA-10000577,780,960,5,2,19.2,940.8,160.8
4,5,2022-07-13,Standard Class,Consumer,United States,Fort Lauderdale,Florida,33311,South,Office Supplies,Storage,OFF-ST-10000760,20,20,2,5,1.0,19.0,-1.0

In [9]:
#5 convert order date from object data type to datetime
df['order_date']=pd.to_datetime(df['order_date'],format= "%Y-%m-%d")
df.dtypes

order_id                     int64
order_date          datetime64[ns]
ship_mode                   object
segment                     object
country                     object
city                        object
state                       object
postal_code                  int64
region                      object
category                    object
sub_category                object
product_id                  object
cost_price                   int64
list_price                   int64
quantity                     int64
discount_percent             int64
discount                   float64
sale_price                 float64
profit                     float64
dtype: object

In [10]:
#6 drop cost price,list price & discount percent columns.
df.drop(columns=['list_price','cost_price','discount_percent'],inplace = True)

In [69]:
!pip install pymysql

Collecting pymysql
  Downloading PyMySQL-1.1.0-py3-none-any.whl (44 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.0

WARNING: You are using pip version 21.1.1; however, version 24.0 is available.
You should consider upgrading via the 'c:\users\lenovo\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.

In [88]:
!pip install sqlalchemy

Collecting sqlalchemy
  Downloading SQLAlchemy-2.0.30-cp38-cp38-win_amd64.whl (2.1 MB)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\lenovo\appdata\local\programs\python\python38\lib\site-packages (from sqlalchemy) (4.11.0)
Collecting greenlet!=0.4.17
  Downloading greenlet-3.0.3-cp38-cp38-win_amd64.whl (290 kB)
Installing collected packages: greenlet, sqlalchemy
Successfully installed greenlet-3.0.3 sqlalchemy-2.0.30

WARNING: You are using pip version 21.1.1; however, version 24.0 is available.
You should consider upgrading via the 'c:\users\lenovo\appdata\local\programs\python\python38\python.exe -m pip install --upgrade pip' command.

In [117]:
import pymysql
from sqlalchemy import create_engine

In [ ]:
#7 Load the data into mysql server using append option
engine = create_engine('mysql+pymysql://root:vip@Localhost/retail_orders')
df.to_sql('orders',engine,if_exists='append',index=False)

In [143]:
#7 Load the data into mysql server using replace option
engine = create_engine('mysql+pymysql://root:vip@Localhost/retail_orders')
df.to_sql('orders',engine,if_exists='replace',index=False)
print ('Data has been uploaded')

Data has been uploaded